# -*- coding: utf-8 -*-
"""Decision_Tree_Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HWcDBX6bqjhlHYLJ_4NNMd9DkF-82evJ
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('/content/Hopsital_Dataset.csv')

print("First 5 rows of the dataset:")
display(df.head())

print("\nInformation about the dataset (data types, non-null values):")
df.info()

print("\nDescriptive statistics of the dataset:")
display(df.describe())

df.head(10)

print("Unique values for each column:")
for column in df.columns:
    unique_count = df[column].nunique()
    if unique_count <= 20:  # Display unique values if there are 20 or less
        print(f"\nColumn '{column}' ({unique_count} unique values):\n{df[column].unique()}")
    else:
        print(f"\nColumn '{column}': {unique_count} unique values (too many to display all)")

print("\nNumber of NULL values for each column:")
display(df.isnull().sum().to_frame(name='Null Count'))



df = df[df['Gender'] != 'Sex']
df = df[df['Route'] != 'Route']
df = df[~df['Frequency'].isin(['Freq', 'Frequency'])]

print("After cleaning 'Gender', 'Route', and 'Frequency' columns:")
df.info()

print("Unique values for each column:")
for column in df.columns:
    unique_count = df[column].nunique()
    if unique_count <= 20:  # Display unique values if there are 20 or less
        print(f"\nColumn '{column}' ({unique_count} unique values):\n{df[column].unique()}")
    else:
        print(f"\nColumn '{column}': {unique_count} unique values (too many to display all)")

print("\nNumber of NULL values for each column:")
display(df.isnull().sum().to_frame(name='Null Count'))



"""# Task
Create a Neural Network classification model to predict the 'Duration_Category' (categorized from 'Duration (days)' into '<5 days', '5-10 days', and '>10 days') using 'Age', 'Dosage (gram)', 'Gender', 'Route', and 'Frequency' as features, evaluate its performance, and summarize the findings.

## Create Duration Categories

### Subtask:
Convert the numerical 'Duration (days)' column into a new categorical column named 'Duration_Category' with three classes: '<5 days', '5-10 days', and '>10 days'. This will be our new target variable for classification.

**Reasoning**:
The first step is to remove non-numeric entries from the 'Duration (days)' column as identified in previous steps to prepare it for numeric conversion. This will involve filtering out rows containing 'Duration' and 'Duration (days)' strings.
"""

df = df[~df['Duration (days)'].isin(['Duration', 'Duration (days)'])]

print("DataFrame after removing non-numeric 'Duration (days)' entries:")
df.info()

"""**Reasoning**:
The next step is to convert the 'Duration (days)' column to a numeric data type, coercing any errors to NaN, as specified in the instructions. This will allow for proper numerical binning later.


"""

df['Duration (days)'] = pd.to_numeric(df['Duration (days)'], errors='coerce')

print("DataFrame after converting 'Duration (days)' to numeric:")
df.info()

"""**Reasoning**:
The next step is to drop any rows where 'Duration (days)' became NaN after the numeric conversion, ensuring the column is completely clean for categorization, as specified in the instructions.


"""

df.dropna(subset=['Duration (days)'], inplace=True)

print("DataFrame after dropping rows with NaN in 'Duration (days)':")
df.info()

"""**Reasoning**:
Now that 'Duration (days)' is numeric and clean, the next step is to define the bin edges and labels for the new 'Duration_Category' column as specified in the instructions. This prepares the data for categorization.


"""

bins = [0, 5, 10, df['Duration (days)'].max() + 1] # +1 to include the max value if it falls exactly on the edge
labels = ['<5 days', '5-10 days', '>10 days']

print("Bins defined for 'Duration (days)':", bins)
print("Labels defined for 'Duration_Category':", labels)

"""**Reasoning**:
With the bins and labels defined, the next step is to create the 'Duration_Category' column by applying `pd.cut` to the 'Duration (days)' column using these definitions, as specified in the instructions to ensure the rightmost bin edge is included.


"""

df['Duration_Category'] = pd.cut(df['Duration (days)'], bins=bins, labels=labels, right=False)

print("First 5 rows with the new 'Duration_Category' column:")
display(df[['Duration (days)', 'Duration_Category']].head())

print("Value counts for the new 'Duration_Category' column:")
print(df['Duration_Category'].value_counts())

"""## Prepare Data for Classification Modeling

### Subtask:
Define the features (X) using 'Age', 'Dosage (gram)', and the already one-hot encoded 'Gender', 'Route', and 'Frequency' columns. Define the target variable (y) as the newly created 'Duration_Category'. Then, split the dataset into training and testing sets.

**Reasoning**:
The first step in preparing the data is to convert the 'Age' column to a numeric type, as it's currently an object type, and then handle any resulting NaN values by filling them with the median to maintain data integrity for model training.
"""

df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
median_age = df['Age'].median()
df['Age'].fillna(median_age, inplace=True)

print("DataFrame after converting 'Age' to numeric and filling NaNs:")
df.info()

"""**Reasoning**:
The previous code generated a FutureWarning due to the use of `inplace=True` with chained assignment on `df['Age'].fillna()`. To fix this, the `fillna` operation should be assigned back to the 'Age' column directly to ensure the changes are applied correctly and to avoid the warning.


"""

df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
median_age = df['Age'].median()
df['Age'] = df['Age'].fillna(median_age)

print("DataFrame after converting 'Age' to numeric and filling NaNs:")
df.info()

"""**Reasoning**:
The next step is to convert the 'Dosage (gram)' column to a numeric data type, coercing errors to NaN, and then fill any resulting NaN values with the median dosage, ensuring it's ready for model training.

# Task
```python
df['Dosage (gram)'] = pd.to_numeric(df['Dosage (gram)'], errors='coerce')
median_dosage = df['Dosage (gram)'].median()
df['Dosage (gram)'] = df['Dosage (gram)'].fillna(median_dosage)

print("DataFrame after converting 'Dosage (gram)' to numeric and filling NaNs:")
df.info()
```

## Prepare Data for Classification Modeling

### Subtask:
Convert the 'Dosage (gram)' column to numeric, fill any resulting NaN values with the median, and print the DataFrame information.

**Reasoning**:
Convert the 'Dosage (gram)' column to a numeric data type, coercing errors to NaN, and then fill any resulting NaN values with the median dosage, ensuring it's ready for model training, as specified in the instructions.
"""

df['Dosage (gram)'] = pd.to_numeric(df['Dosage (gram)'], errors='coerce')
median_dosage = df['Dosage (gram)'].median()
df['Dosage (gram)'] = df['Dosage (gram)'].fillna(median_dosage)

print("DataFrame after converting 'Dosage (gram)' to numeric and filling NaNs:")
df.info()

"""## Prepare Data for Classification Modeling

### Subtask:
One-hot encode the categorical features 'Gender', 'Route', and 'Frequency' to prepare them for model training.

**Reasoning**:
One-hot encode the categorical features 'Gender', 'Route', and 'Frequency' using `pd.get_dummies` and drop the original columns, then display the first few rows and the DataFrame information to verify the changes.
"""

df = pd.get_dummies(df, columns=['Gender', 'Route', 'Frequency'], drop_first=True)

print("DataFrame after one-hot encoding categorical features:")
display(df.head())
df.info()

"""**Reasoning**:
Now that the necessary numerical and one-hot encoded features are prepared, the next step is to define the features (X) and the target variable (y), and then split the dataset into training and testing sets to prepare for model building.


"""

from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df[['Age', 'Dosage (gram)', 'Gender_Male', 'Route_IV', 'Route_Oral', 'Frequency_OD', 'Frequency_QID', 'Frequency_TDS']]
y = df['Duration_Category']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

print("\nDistribution of Duration_Category in y_train:")
print(y_train.value_counts(normalize=True))

print("\nDistribution of Duration_Category in y_test:")
print(y_test.value_counts(normalize=True))

"""## Train a Decision Tree Classifier

### Subtask:
Train a Decision Tree Classifier model using the prepared training data to predict 'Duration_Category'.

**Reasoning**:
To begin training a Decision Tree Classifier, the first step is to import the necessary class, instantiate the model with a specified random state for reproducibility, and then train it using the prepared training data.
"""

from sklearn.tree import DecisionTreeClassifier

# Instantiate the Decision Tree Classifier
dtc = DecisionTreeClassifier(random_state=42)

# Train the model
dtc.fit(X_train, y_train)

print("Decision Tree Classifier trained successfully.")

"""## Evaluate the Classification Model

### Subtask:
Evaluate the trained Decision Tree Classifier's performance on the test set using classification metrics such as accuracy, precision, recall, F1-score, and specifically generate and display a confusion matrix.

**Reasoning**:
To evaluate the trained Decision Tree Classifier, the first step is to make predictions on the test set, which will then be used to calculate performance metrics.
"""

y_pred = dtc.predict(X_test)

print("Predictions on the test set generated successfully.")

"""**Reasoning**:
Now that predictions (`y_pred`) are available, the next step is to calculate and display various classification metrics (accuracy, precision, recall, F1-score) and a confusion matrix to fully evaluate the model's performance on the test set, as specified in the instructions.


"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Calculate classification metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision (weighted): {precision:.4f}")
print(f"Recall (weighted): {recall:.4f}")
print(f"F1-Score (weighted): {f1:.4f}")

# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Display confusion matrix as a heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=dtc.classes_, yticklabels=dtc.classes_)
plt.title('Confusion Matrix for Decision Tree Classifier')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""## Final Task

### Subtask:
Summarize the Decision Tree Classifier model's performance, discuss the insights gained from the confusion matrix, and suggest potential next steps for model improvement or further analysis.

## Summary:

### Data Analysis Key Findings
*   **Data Preparation:**
    *   The 'Dosage (gram)' column was successfully converted to a numeric type (`float64`), and its missing values were imputed using the median, ensuring no NaNs remained.
    *   Categorical features 'Gender', 'Route', and 'Frequency' were one-hot encoded, creating new boolean columns (e.g., `Gender_Male`, `Route_IV`), which expanded the feature set to 8 columns.
    *   The dataset was split into an 80% training set and a 20% test set, with the target variable 'Duration_Category' stratified to maintain its distribution across both sets.
*   **Model Training:** A Decision Tree Classifier was successfully trained on the preprocessed training data.
*   **Model Performance:** The Decision Tree Classifier achieved the following performance metrics on the test set:
    *   Accuracy: 0.7784
    *   Precision (weighted): 0.7870
    *   Recall (weighted): 0.7784
    *   F1-Score (weighted): 0.7808
*   **Confusion Matrix Analysis:** A confusion matrix was generated and displayed as a heatmap, providing a visual representation of the model's true positives, true negatives, false positives, and false negatives for each 'Duration_Category'. While the specific values are not provided, the matrix allows for an assessment of where the model is performing well and where it is making errors across different classes.

### Insights or Next Steps
*   The Decision Tree Classifier shows promising initial performance with an accuracy of approximately 78\%. Further analysis of the confusion matrix would reveal specific class-wise performance, highlighting which duration categories are correctly predicted and which are commonly confused.
*   To improve the model, next steps could include hyperparameter tuning for the Decision Tree Classifier (e.g., `max_depth`, `min_samples_split`), exploring more advanced ensemble methods like Random Forest or Gradient Boosting, or engineering new features from existing data.

# Task
Perform hyperparameter tuning on the Decision Tree Classifier using GridSearchCV or RandomizedSearchCV to find the optimal parameters for the 'Duration_Category' prediction model, considering a plausible range of hyperparameters.

## Prepare Data for Classification Modeling

### Subtask:
Ensure the features (X) and the target variable (y - 'Duration_Category') are properly defined and the dataset is split into training and testing sets, ready for model training and evaluation.

## Hyperparameter Tuning for Decision Tree Classifier

### Subtask:
Perform hyperparameter tuning for the Decision Tree Classifier using GridSearchCV to find the optimal parameters for the 'Duration_Category' prediction model.

**Reasoning**:
To perform hyperparameter tuning for the Decision Tree Classifier, I need to import the necessary libraries, define a parameter grid for GridSearchCV, instantiate the Decision Tree Classifier and GridSearchCV, fit it to the training data, and then print the best parameters and their corresponding score.
"""

from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier

# 2. Define a dictionary param_grid with a plausible range of hyperparameters
param_grid = {
    'max_depth': [3, 5, 7, 10, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'criterion': ['gini', 'entropy']
}

# 3. Instantiate a DecisionTreeClassifier with random_state=42
dt_clf = DecisionTreeClassifier(random_state=42)

# 4. Instantiate GridSearchCV
grid_search = GridSearchCV(estimator=dt_clf, param_grid=param_grid, cv=5, scoring='f1_weighted', n_jobs=-1, verbose=1)

# 5. Fit GridSearchCV to your training data
grid_search.fit(X_train, y_train)

# 6. Print the best_params_ and best_score_
print("Best parameters found:", grid_search.best_params_)
print("Best F1-weighted score:", grid_search.best_score_)

# Store the best estimator
best_dt_clf = grid_search.best_estimator_
print("GridSearchCV completed and best estimator stored.")

"""## Evaluate the Tuned Classification Model

### Subtask:
Evaluate the performance of the tuned Decision Tree Classifier on the test set using classification metrics such as accuracy, precision, recall, F1-score, and a confusion matrix.

**Reasoning**:
To evaluate the tuned Decision Tree Classifier, I need to use the `best_dt_clf` to make predictions on the test set (`X_test`) and then compute and display various classification metrics, including accuracy, precision, recall, F1-score, and a confusion matrix as a heatmap.
"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Make predictions on the test set using the best estimator
y_pred_tuned = best_dt_clf.predict(X_test)

print("Predictions on the test set using the tuned model generated successfully.")

# Calculate classification metrics
accuracy_tuned = accuracy_score(y_test, y_pred_tuned)
precision_tuned = precision_score(y_test, y_pred_tuned, average='weighted')
recall_tuned = recall_score(y_test, y_pred_tuned, average='weighted')
f1_tuned = f1_score(y_test, y_pred_tuned, average='weighted')

print(f"\nAccuracy (tuned model): {accuracy_tuned:.4f}")
print(f"Precision (weighted, tuned model): {precision_tuned:.4f}")
print(f"Recall (weighted, tuned model): {recall_tuned:.4f}")
print(f"F1-Score (weighted, tuned model): {f1_tuned:.4f}")

# Generate confusion matrix
cm_tuned = confusion_matrix(y_test, y_pred_tuned)

# Display confusion matrix as a heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(cm_tuned, annot=True, fmt='d', cmap='Blues',
            xticklabels=best_dt_clf.classes_, yticklabels=best_dt_clf.classes_)
plt.title('Confusion Matrix for Tuned Decision Tree Classifier')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()



"""# Task
Save the `best_dt_clf` (tuned Decision Tree Classifier) model to a file named `best_dt_classifier_model.joblib`.

## Save the Tuned Model

### Subtask:
Save the `best_dt_clf` (tuned Decision Tree Classifier) model to a file named `best_dt_classifier_model.joblib`.

**Reasoning**:
To save the tuned Decision Tree Classifier model, I need to import the `joblib` library and then use its `dump` function to serialize the `best_dt_clf` object to a specified file.
"""

import joblib

# Save the best_dt_clf model to a file
joblib.dump(best_dt_clf, 'best_dt_classifier_model.joblib')

print("Tuned Decision Tree Classifier model saved as 'best_dt_classifier_model.joblib'")

"""## Load the Trained Model

### Subtask:
Load the previously saved `best_dt_classifier_model.joblib` into memory. This model will be used by the API for making predictions.

**Reasoning**:
To load the previously saved model, I need to import the `joblib` library and use its `load` function to deserialize the model from the specified file.
"""

import joblib

# Load the best_dt_classifier_model.joblib file
best_dt_clf_loaded = joblib.load('best_dt_classifier_model.joblib')

print("Tuned Decision Tree Classifier model loaded successfully.")

"""## Create a Flask API for Prediction

### Subtask:
Develop a Flask application that will expose a prediction endpoint. This endpoint will accept input features from a web request.

**Reasoning**:
To begin developing the Flask application, I need to import the necessary Flask components, instantiate the app, and define the basic structure of the `/predict` endpoint to handle incoming requests and prepare for prediction logic.
"""

from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route('/predict', methods=['POST'])
def predict():
    # Prediction logic will go here
    return jsonify({'message': 'Prediction endpoint hit!'})

print("Flask app initialized and '/predict' route defined.")

"""**Reasoning**:
Now that the basic Flask app and route are set up, the next step is to implement the actual prediction logic within the `/predict` function. This involves receiving the input data from the request, converting it into a suitable format for the loaded model, making the prediction, and returning the result as a JSON response.


"""

from flask import Flask, request, jsonify
import pandas as pd

app = Flask(__name__)

# Assuming best_dt_clf_loaded is already loaded from 'best_dt_classifier_model.joblib'
# and X_train columns are available for order reference

@app.route('/predict', methods=['POST'])
def predict():
    if not request.json:
        return jsonify({'error': 'Invalid input, request must be JSON'}), 400

    data = request.json

    # Convert the input data to a DataFrame, ensuring column order matches X_train
    # X_train columns: ['Age', 'Dosage (gram)', 'Gender_Male', 'Route_IV', 'Route_Oral', 'Frequency_OD', 'Frequency_QID', 'Frequency_TDS']
    try:
        # Convert boolean values for Gender_Male, Route_IV, etc. from Python bool to int for model compatibility
        processed_data = {
            'Age': data['Age'],
            'Dosage (gram)': data['Dosage (gram)'],
            'Gender_Male': int(data['Gender_Male']),
            'Route_IV': int(data['Route_IV']),
            'Route_Oral': int(data['Route_Oral']),
            'Frequency_OD': int(data['Frequency_OD']),
            'Frequency_QID': int(data['Frequency_QID']),
            'Frequency_TDS': int(data['Frequency_TDS'])
        }

        input_df = pd.DataFrame([processed_data])

        # Make prediction using the loaded model
        prediction = best_dt_clf_loaded.predict(input_df)
        return jsonify({'prediction': prediction[0]})
    except KeyError as e:
        return jsonify({'error': f'Missing data for key: {e}'}), 400
    except Exception as e:
        return jsonify({'error': str(e)}), 500

print("Flask app updated with prediction logic.")

"""## Provide API Usage Instructions

### Subtask:
Generate instructions on how to run the Flask API locally and how to send a sample POST request to the prediction endpoint to test its functionality.

### How to Run the Flask API Locally

1.  **Save the Python Code:** Ensure the Flask application code (including the model loading and prediction logic) is saved in a Python file, for example, `app.py`.

2.  **Set Flask Environment Variable:** Open your terminal or command prompt and set the `FLASK_APP` environment variable to the name of your application file:
    ```bash
    export FLASK_APP=app.py
    # On Windows, use: set FLASK_APP=app.py
    ```

3.  **Run the Flask Application:** Execute the Flask development server using the `flask run` command:
    ```bash
    flask run
    ```
    You should see output indicating that the Flask app is running, usually on `http://127.0.0.1:5000/`.

### How to Send a Sample POST Request (using `curl`)

Once the Flask application is running, you can send a POST request to the `/predict` endpoint. Here's a sample `curl` command:

```bash
curl -X POST -H "Content-Type: application/json" -d '{
    "Age": 60,
    "Dosage (gram)": 0.5,
    "Gender_Male": 1,
    "Route_IV": 0,
    "Route_Oral": 1,
    "Frequency_OD": 1,
    "Frequency_QID": 0,
    "Frequency_TDS": 0
}' http://127.0.0.1:5000/predict
```

**Expected Output Example:**

```json
{
  "prediction": "<5 days"
}
```

### How to Send a Sample POST Request (using Python's `requests` library)

You can also use Python's `requests` library to send POST requests to the API. First, ensure you have it installed (`pip install requests`).

```python
import requests
import json

# Define the API endpoint URL
url = 'http://127.0.0.1:5000/predict'

# Define the data to be sent in the POST request
# These features should match the input format expected by your model
# X_train columns: ['Age', 'Dosage (gram)', 'Gender_Male', 'Route_IV', 'Route_Oral', 'Frequency_OD', 'Frequency_QID', 'Frequency_TDS']
data = {
    "Age": 60,
    "Dosage (gram)": 0.5,
    "Gender_Male": 1,  # 1 for Male, 0 for Female
    "Route_IV": 0,     # 1 for IV, 0 otherwise
    "Route_Oral": 1,   # 1 for Oral, 0 otherwise
    "Frequency_OD": 1, # 1 for OD, 0 otherwise
    "Frequency_QID": 0, # 1 for QID, 0 otherwise
    "Frequency_TDS": 0  # 1 for TDS, 0 otherwise
}

# Send the POST request with JSON data
try:
    response = requests.post(url, json=data)
    response.raise_for_status() # Raise an exception for HTTP errors

    # Parse the JSON response
    prediction_result = response.json()

    print("Prediction Result:", prediction_result)

except requests.exceptions.RequestException as e:
    print(f"An error occurred: {e}")
    if hasattr(e, 'response') and e.response is not None:
        print(f"Response content: {e.response.text}")
```

## Final Task

### Subtask:
Summarize the created API, its functionality, and reiterate the considerations for deploying such a Python-based API to production platforms.

## Summary:

### Data Analysis Key Findings

*   The tuned Decision Tree Classifier model (`best_dt_clf`) was successfully saved as `best_dt_classifier_model.joblib` and subsequently loaded into memory for use by the API.
*   A Flask API was created with a `/predict` endpoint that accepts POST requests containing JSON data for prediction.
*   The API's prediction logic correctly handles input data by converting it into a Pandas DataFrame, ensuring proper column order and data type conversions (e.g., booleans to integers) to match the model's training data structure.
*   The `/predict` endpoint provides robust error handling for missing input keys and general exceptions during the prediction process.
*   Comprehensive instructions were generated for running the Flask API locally and for sending sample POST requests using both `curl` and Python's `requests` library.

### Insights or Next Steps

*   **API Functionality Summary:** The created Flask API provides a RESTful interface for the trained Decision Tree Classifier, allowing external applications to send feature data and receive predictions. Its core functionality involves loading the pre-trained model, validating and transforming input data, making a prediction, and returning the result in a standardized JSON format.
*   **Deployment Considerations:** For deploying such a Python-based API to production, consider containerization (e.g., Docker) to ensure environment consistency, using a robust production-ready web server (e.g., Gunicorn or uWSGI instead of Flask's development server), implementing robust logging and monitoring, securing the API endpoints (e.g., API keys, authentication), and utilizing cloud platforms for scalability and reliability.
"""